# Generated by Django 4.2.3 on 2023-08-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.IntegerField(choices=[(1, 'pomoc'), (2, 'nauczyciel'), (3, 'inna')], default=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
