# Generated by Django 4.2.3 on 2023-08-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_address_teacher_city_teacher_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
    ]
