# Generated by Django 4.2.3 on 2023-08-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_remove_groups_teacher'),
        ('teacher', '0005_remove_teacher_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='children.groups'),
        ),
    ]
