# Generated by Django 4.2.3 on 2023-08-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_remove_groups_teacher'),
        ('teacher', '0006_teacher_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(to='children.groups'),
        ),
    ]
