# Generated by Django 4.2.3 on 2023-08-08 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0005_remove_groups_teacher'),
        ('director', '0021_remove_director_address_remove_director_city_and_more'),
        ('teacher', '0007_remove_teacher_group_teacher_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Employee',
        ),
    ]
