# Generated by Django 4.2.3 on 2023-08-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta')], null=True),
        ),
    ]
