# Generated by Django 4.2.3 on 2023-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teacher', '0012_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.ManyToManyField(to='groups.groups'),
        ),
    ]
