# Generated by Django 4.2.3 on 2023-08-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teacher', '0013_alter_employee_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
