# Generated by Django 4.2.14 on 2025-12-31 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0041_alter_director_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0016_remove_employee_principal_alter_employee_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('user', 'kindergarten')},
        ),
    ]
