# Generated by Django 4.2.14 on 2025-12-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meals_kindergarten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='principal',
        ),
    ]
