# Generated by Django 4.2.3 on 2023-07-08 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 9, 38, 55, 126464, tzinfo=datetime.timezone.utc)),
        ),
    ]
