# Generated by Django 4.2.3 on 2023-07-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groups_kid_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='kid',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parent'),
        ),
    ]
