# Generated by Django 4.2.3 on 2023-07-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_kid_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='group',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='payment_plan',
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
    ]
