# Generated by Django 4.2.3 on 2023-07-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kid_last_name_kid_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='kid',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kid',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Chłopiec'), (2, 'Dziewczynka')], null=True),
        ),
        migrations.AddField(
            model_name='kid',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.groups'),
        ),
        migrations.AddField(
            model_name='kid',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='kid',
            name='parents',
        ),
        migrations.AddField(
            model_name='kid',
            name='payment_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentplan'),
        ),
        migrations.AddField(
            model_name='kid',
            name='parents',
            field=models.ManyToManyField(to='accounts.parent'),
        ),
    ]
