# Generated by Django 4.2.3 on 2023-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_kid_group_remove_kid_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.TextField(choices=[('parent', 'parent'), ('teacher', 'teacher'), ('director', 'director')], default='director'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
