# Generated by Django 4.2.3 on 2023-07-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_permission_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.TextField(choices=[('parent', 'parent'), ('teacher', 'teacher'), ('director', 'director')], default='director'),
        ),
    ]
