# Generated by Django 4.2.3 on 2023-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_paymentplan_kid_end_kid_gender_kid_group_kid_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=7),
        ),
    ]
