# Generated by Django 4.2.3 on 2023-07-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_meals_paymentplan_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentplan',
            old_name='type',
            new_name='name',
        ),
    ]
