# Generated by Django 4.2.3 on 2023-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_type_paymentplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
