# Generated by Django 4.2.3 on 2023-07-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_kid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='payment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentplan'),
        ),
    ]
