# Generated by Django 4.2.3 on 2023-07-07 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_kid_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Chłopiec'), (2, 'Dziewczynka')], default=1),
        ),
        migrations.AlterField(
            model_name='kid',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.groups'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='last_name',
            field=models.CharField(default='cos', max_length=128),
        ),
        migrations.AlterField(
            model_name='kid',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentplan'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 15, 24, 14, 672035, tzinfo=datetime.timezone.utc)),
        ),
    ]
