# Generated by Django 4.2.3 on 2023-08-07 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0018_alter_kid_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('principal', models.ManyToManyField(to='director.director')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=7)),
                ('principal', models.ManyToManyField(to='director.director')),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('principal', models.ManyToManyField(to='director.director')),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.IntegerField(choices=[(1, 'Chłopiec'), (2, 'Dziewczynka')], default=1)),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('end', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.groups')),
                ('kid_meals', models.ManyToManyField(to='children.meals')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.paymentplan')),
                ('principal', models.ManyToManyField(to='director.director')),
            ],
        ),
    ]
