# Generated by Django 4.2.3 on 2023-08-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0019_remove_kid_group_remove_kid_kid_meals_and_more'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='principal',
        ),
        migrations.AddField(
            model_name='groups',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director'),
        ),
        migrations.AddField(
            model_name='kid',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director'),
        ),
        migrations.AddField(
            model_name='meals',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director'),
        ),
    ]
