# Generated by Django 4.2.3 on 2023-08-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_group'),
        ('children', '0003_remove_paymentplan_principal_paymentplan_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
