# Generated by Django 4.2.3 on 2023-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_groups_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='teacher',
        ),
    ]
