# Generated by Django 4.2.3 on 2023-08-09 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_groups_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='capacity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
