# Generated by Django 4.2.3 on 2023-08-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0009_alter_groups_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='image',
        ),
    ]
