# Generated by Django 4.2.3 on 2023-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0027_alter_mealphotos_principal'),
        ('children', '0010_remove_groups_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='photo',
            field=models.ManyToManyField(to='director.groupphotos'),
        ),
        migrations.AddField(
            model_name='meals',
            name='photo',
            field=models.ManyToManyField(to='director.mealphotos'),
        ),
    ]
