# Generated by Django 4.2.3 on 2023-08-10 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0011_groups_photo_meals_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2023, 8, 10, 12, 19, 18, 293389, tzinfo=datetime.timezone.utc))),
                ('presenceType', models.IntegerField(choices=[(1, 'Nieobeconsc'), (2, 'Obecnosc'), (3, 'Planowana nieobecnosc'), (4, 'dzien wolny')])),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.kid')),
            ],
        ),
    ]
