# Generated by Django 4.2.3 on 2023-08-10 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0014_alter_presencemodel_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencemodel',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 8, 10, 18, 12, 31, 153110, tzinfo=datetime.timezone.utc)),
        ),
    ]
