# Generated by Django 4.2.3 on 2023-08-11 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0016_meals_per_day_alter_presencemodel_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kid',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='presencemodel',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 8, 11, 11, 0, 20, 771540, tzinfo=datetime.timezone.utc)),
        ),
    ]
