# Generated by Django 4.2.3 on 2023-08-14 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0017_groups_is_active_kid_is_active_meals_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='yearbook',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='presencemodel',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 11, 2, 32, 346713, tzinfo=datetime.timezone.utc)),
        ),
    ]
