# Generated by Django 4.2.3 on 2023-08-14 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0019_alter_presencemodel_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencemodel',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 11, 58, 9, 456136, tzinfo=datetime.timezone.utc)),
        ),
    ]
