# Generated by Django 4.2.3 on 2023-08-14 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0022_alter_presencemodel_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='children.groups'),
        ),
        migrations.AlterField(
            model_name='presencemodel',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 16, 8, 17, 779747, tzinfo=datetime.timezone.utc)),
        ),
    ]
