# Generated by Django 4.2.3 on 2023-08-14 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0025_alter_presencemodel_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='kid_meals',
        ),
        migrations.AlterField(
            model_name='kid',
            name='payment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='children.paymentplan'),
        ),
        migrations.AlterField(
            model_name='presencemodel',
            name='day',
            field=models.DateField(auto_created=datetime.datetime(2023, 8, 14, 16, 51, 55, 367767, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='kid',
            name='kid_meals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='children.meals'),
        ),
    ]
