# Generated by Django 4.2.3 on 2023-08-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0031_alter_presencemodel_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
