# Generated by Django 4.2.3 on 2023-08-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0032_alter_paymentplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='principal',
        ),
    ]
