# Generated by Django 4.2.3 on 2023-08-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teacher', '0013_alter_employee_group'),
        ('children', '0033_remove_groups_photo_remove_groups_principal'),
        ('blog', '0004_alter_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
