# Generated by Django 4.2.3 on 2023-08-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0034_alter_kid_group_delete_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='principal',
        ),
    ]
