# Generated by Django 4.2.3 on 2023-08-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0036_alter_kid_kid_meals'),
        ('payments_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='payment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments_plans.paymentplan'),
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
    ]
