# Generated by Django 4.2.3 on 2023-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0037_alter_kid_payment_plan_delete_meals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
