# Generated by Django 4.2.3 on 2023-08-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0038_kid_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(auto_created=True),
        ),
    ]
