# Generated by Django 4.2.14 on 2025-12-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0039_alter_kid_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Miesiąc')),
                ('year', models.IntegerField(verbose_name='Rok')),
                ('tuition_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Czesne')),
                ('meals_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wyżywienie')),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zaległości')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Suma do zapłaty')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kwota wpłacona')),
                ('status', models.CharField(choices=[('unpaid', 'Nieopłacona'), ('partial', 'Opłacona częściowo'), ('paid', 'Opłacona'), ('overdue', 'Zaległość')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(verbose_name='Termin płatności')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='children.kid')),
            ],
            options={
                'verbose_name': 'Rozliczenie',
                'verbose_name_plural': 'Rozliczenia',
                'unique_together': {('kid', 'month', 'year')},
            },
        ),
    ]
