# Generated by Django 4.2.14 on 2025-12-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0037_alter_contactmodel_options_and_more'),
        ('children', '0040_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='director.director'),
        ),
    ]
