# Generated by Django 4.2.3 on 2023-07-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0014_remove_director_groups_remove_director_kids_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.ManyToManyField(to='director.director'),
        ),
    ]
