# Generated by Django 4.2.3 on 2023-08-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('blog', '0002_post_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(to='children.groups'),
        ),
    ]
