# Generated by Django 4.2.14 on 2025-12-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_title_remove_post_group_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('holiday', 'Święto / Wolne'), ('trip', 'Wycieczka'), ('meeting', 'Spotkanie'), ('performance', 'Występ / Teatrzyk'), ('info', 'Ogólne')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Ogłoszenie', max_length=200),
        ),
    ]
