# Generated by Django 4.2.14 on 2025-12-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0039_kindergarten_remove_contactmodel_kindergarten_name_and_more'),
        ('blog', '0007_post_category_post_event_date_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.kindergarten'),
        ),
    ]
