# Generated by Django 4.2.14 on 2025-12-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_kindergarten'),
        ('blog', '0008_post_kindergarten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(blank=True, to='groups.groups'),
        ),
    ]
