# Generated by Django 4.2.3 on 2023-07-10 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'permissions': [('is_director', 'Is the director of kindergarten')]},
        ),
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 11, 53, 37, 353212, tzinfo=datetime.timezone.utc)),
        ),
    ]
