# Generated by Django 4.2.3 on 2023-07-10 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 10, 34, 23, 391145, tzinfo=datetime.timezone.utc)),
        ),
    ]
