# Generated by Django 4.2.3 on 2023-07-10 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_alter_director_options_alter_kid_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 12, 5, 17, 86714, tzinfo=datetime.timezone.utc)),
        ),
    ]
