# Generated by Django 4.2.3 on 2023-07-10 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0007_alter_kid_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='parent',
        ),
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 16, 38, 7, 191938, tzinfo=datetime.timezone.utc)),
        ),
    ]
