# Generated by Django 4.2.3 on 2023-07-10 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0008_remove_director_parent_remove_kid_parents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 16, 43, 15, 793043, tzinfo=datetime.timezone.utc)),
        ),
    ]
