# Generated by Django 4.2.3 on 2023-07-10 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_parenta_delete_parent'),
        ('director', '0009_alter_kid_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='parent_profiles',
            field=models.ManyToManyField(to='parent.parenta'),
        ),
        migrations.AddField(
            model_name='kid',
            name='parents',
            field=models.ManyToManyField(to='parent.parenta'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 17, 16, 55, 849049, tzinfo=datetime.timezone.utc)),
        ),
    ]
