# Generated by Django 4.2.3 on 2023-07-11 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0010_director_parent_profiles_kid_parents_alter_kid_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='kid_meals',
            field=models.ManyToManyField(to='director.meals'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 18, 21, 23, 67954, tzinfo=datetime.timezone.utc)),
        ),
    ]
