# Generated by Django 4.2.3 on 2023-07-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_alter_parenta_options'),
        ('director', '0014_remove_director_groups_remove_director_kids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='director',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='director',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='director',
            name='parent_profiles',
        ),
        migrations.RemoveField(
            model_name='director',
            name='payment_plan',
        ),
        migrations.AddField(
            model_name='director',
            name='groups',
            field=models.ManyToManyField(to='director.groups'),
        ),
        migrations.AddField(
            model_name='director',
            name='kids',
            field=models.ManyToManyField(to='director.kid'),
        ),
        migrations.AddField(
            model_name='director',
            name='meals',
            field=models.ManyToManyField(to='director.meals'),
        ),
        migrations.AddField(
            model_name='director',
            name='parent_profiles',
            field=models.ManyToManyField(to='parent.parenta'),
        ),
        migrations.AddField(
            model_name='director',
            name='payment_plan',
            field=models.ManyToManyField(to='director.paymentplan'),
        ),
    ]
