# Generated by Django 4.2.3 on 2023-07-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('director', '0015_remove_director_groups_remove_director_kids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='first_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='teachers',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teachers',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
    ]
