# Generated by Django 4.2.3 on 2023-08-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('director', '0016_director_first_name_director_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='teachers',
            field=models.ManyToManyField(null=True, to='teacher.teacher'),
        ),
    ]
