# Generated by Django 4.2.3 on 2023-08-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_group'),
        ('director', '0018_alter_kid_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='group',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='kid_meals',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='payment_plan',
        ),
        migrations.RemoveField(
            model_name='director',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='director',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='director',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='director',
            name='parent_profiles',
        ),
        migrations.RemoveField(
            model_name='director',
            name='payment_plan',
        ),
        migrations.RemoveField(
            model_name='director',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
    ]
