# Generated by Django 4.2.3 on 2023-08-08 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0020_director_address_director_city_director_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='address',
        ),
        migrations.RemoveField(
            model_name='director',
            name='city',
        ),
        migrations.RemoveField(
            model_name='director',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='director',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu w formacie: '+99 999 999 999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('city', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('zip_code', models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Format kodu pocztowego to - 12-123', regex='^(^[0-9]{2}(?:-[0-9]{3})?$)?$)')])),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='director.director')),
            ],
        ),
    ]
