# Generated by Django 4.2.3 on 2023-08-09 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0022_alter_contactmodel_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_photos', models.ImageField(null=True, upload_to='groupPhoto')),
                ('meal_photos', models.ImageField(null=True, upload_to='mealPhoto')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.photos'),
        ),
    ]
