# Generated by Django 4.2.3 on 2023-08-09 22:36

import director.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0023_photos_director_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_photos', models.ImageField(null=True, upload_to=director.models.user_group_path)),
            ],
        ),
        migrations.CreateModel(
            name='MealPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_photos', models.ImageField(null=True, upload_to=director.models.user_meal_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='director',
            name='photos',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AddField(
            model_name='mealphotos',
            name='principal',
            field=models.ManyToManyField(to='director.director'),
        ),
        migrations.AddField(
            model_name='groupphotos',
            name='principal',
            field=models.ManyToManyField(to='director.director'),
        ),
    ]
