# Generated by Django 4.2.3 on 2023-08-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0024_groupphotos_mealphotos_remove_director_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupphotos',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='mealphotos',
            name='principal',
        ),
        migrations.AddField(
            model_name='groupphotos',
            name='principal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director'),
        ),
        migrations.AddField(
            model_name='mealphotos',
            name='principal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director'),
        ),
    ]
