# Generated by Django 4.2.3 on 2023-08-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0026_alter_groupphotos_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealphotos',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director'),
        ),
    ]
