# Generated by Django 4.2.3 on 2023-08-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0027_alter_mealphotos_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupphotos',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
