# Generated by Django 4.2.3 on 2023-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0028_groupphotos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealphotos',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
