# Generated by Django 4.2.3 on 2023-08-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0030_alter_groupphotos_group_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.director')),
            ],
        ),
    ]
