# Generated by Django 4.2.3 on 2023-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0031_freedaysmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedaysmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupphotos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mealphotos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
