# Generated by Django 4.2.3 on 2023-08-22 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0032_freedaysmodel_is_active_groupphotos_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='localization',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu w formacie: '+99 999 999 999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
