# Generated by Django 4.2.3 on 2023-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0033_remove_contactmodel_address_remove_contactmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta')], null=True),
        ),
    ]
