# Generated by Django 4.2.3 on 2023-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0035_groupphotos_date_created_mealphotos_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupphotos',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealphotos',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
