# Generated by Django 4.2.14 on 2025-12-24 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0036_alter_groupphotos_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Dane kontaktowe', 'verbose_name_plural': 'Dane kontaktowe'},
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='localization',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dodatkowe informacje'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Ulica i numer'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='office_hours',
            field=models.CharField(default='08:00 - 16:00', max_length=100, verbose_name='Godziny otwarcia biura'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Strona WWW'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='zip_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email_address',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail placówki'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu w formacie: '+99 999 999 999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
    ]
