# Generated by Django 4.2.14 on 2025-12-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0037_alter_contactmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='kindergarten_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa Przedszkola / Placówki'),
        ),
    ]
