# Generated by Django 4.2.14 on 2025-12-31 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0038_contactmodel_kindergarten_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='kindergarten_name',
        ),
        migrations.AlterField(
            model_name='director',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.kindergarten'),
        ),
        migrations.AddField(
            model_name='director',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.kindergarten'),
        ),
        migrations.AddField(
            model_name='freedaysmodel',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.kindergarten'),
        ),
        migrations.AddField(
            model_name='groupphotos',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.kindergarten'),
        ),
        migrations.AddField(
            model_name='mealphotos',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.kindergarten'),
        ),
    ]
