# Generated by Django 4.2.14 on 2025-12-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0039_kindergarten_remove_contactmodel_kindergarten_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='director',
        ),
        migrations.RemoveField(
            model_name='freedaysmodel',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='groupphotos',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='mealphotos',
            name='principal',
        ),
    ]
