# Generated by Django 4.2.14 on 2025-12-31 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0040_remove_contactmodel_director_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('user', 'kindergarten')},
        ),
    ]
