# Generated by Django 4.2.3 on 2023-07-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'permissions': [('parent', 'parent permission')]},
        ),
    ]
