# Generated by Django 4.2.3 on 2023-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0008_remove_director_parent_remove_kid_parents_and_more'),
        ('parent', '0002_alter_parent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='kid',
            field=models.ManyToManyField(to='director.kid'),
        ),
    ]
