# Generated by Django 4.2.3 on 2023-07-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_parenta_delete_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parenta',
            options={'permissions': [('is_parent', 'parent permission')]},
        ),
    ]
