# Generated by Django 4.2.3 on 2023-08-08 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0007_parenta_kids_parenta_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenta',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parenta',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='parenta',
            name='zip_code',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats or 12-123', regex='^(^[0-9]{2}(?:-[0-9]{3})?$)?$)')]),
        ),
    ]
