# Generated by Django 4.2.3 on 2023-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0008_parenta_address_parenta_city_parenta_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
