# Generated by Django 4.2.3 on 2023-08-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0009_parenta_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parenta',
            name='is_active',
        ),
    ]
