# Generated by Django 4.2.3 on 2023-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0011_alter_parenta_phone_alter_parenta_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenta',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta')], null=True),
        ),
    ]
