# Generated by Django 4.2.14 on 2025-12-31 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0041_alter_director_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parent', '0014_remove_parenta_principal_alter_parenta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='parenta',
            unique_together={('user', 'kindergarten')},
        ),
    ]
