# Generated by Django 4.2.3 on 2023-08-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0032_freedaysmodel_is_active_groupphotos_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director')),
            ],
        ),
    ]
