# Generated by Django 4.2.14 on 2025-12-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='age_range',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Miesięcznie'), ('quarterly', 'Kwartalnie'), ('annually', 'Rocznie')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='terms_discounts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
