# Generated by Django 4.2.14 on 2025-12-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_plans', '0002_paymentplan_age_range_paymentplan_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentplan',
            old_name='terms_discounts',
            new_name='discount_info',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='age_range',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Miesięcznie'), ('quarterly', 'Kwartalnie'), ('annually', 'Rocznie'), ('onetime', 'Jednorazowo')], default='monthly', max_length=20),
        ),
    ]
