# Generated by Django 4.2.14 on 2025-12-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_remove_employee_group_employee_group'),
        ('payments_plans', '0003_rename_terms_discounts_paymentplan_discount_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pensja zasadnicza')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Premia')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Czy wypłacono?')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data przelewu')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='teacher.employee')),
            ],
            options={
                'verbose_name': 'Wypłata',
                'verbose_name_plural': 'Wypłaty',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
