# Generated by Django 4.2.14 on 2025-12-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_plans', '0006_paymentplan_kindergarten_salarypayment_kindergarten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='principal',
        ),
    ]
