# Generated by Django 4.2.3 on 2023-07-09 16:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(default='cos', max_length=128)),
                ('gender', models.IntegerField(choices=[(1, 'Chłopiec'), (2, 'Dziewczynka')], default=1)),
                ('start', models.DateField(default=datetime.datetime(2023, 7, 9, 16, 14, 54, 73435, tzinfo=datetime.timezone.utc))),
                ('end', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_user.groups')),
                ('parents', models.ManyToManyField(to='parent.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(to='super_user.groups')),
                ('kids', models.ManyToManyField(to='super_user.kid')),
                ('meals', models.ManyToManyField(to='super_user.meals')),
                ('parent', models.ManyToManyField(to='parent.parent')),
                ('payment_plan', models.ManyToManyField(to='super_user.paymentplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kid',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_user.paymentplan'),
        ),
    ]
