# Generated by Django 4.2.3 on 2023-08-17 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0032_freedaysmodel_is_active_groupphotos_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('capacity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('is_active', models.BooleanField(default=True)),
                ('yearbook', models.IntegerField(null=True)),
                ('photo', models.ManyToManyField(to='director.groupphotos')),
                ('principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director')),
            ],
        ),
    ]
