# Generated by Django 4.2.14 on 2025-12-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0039_kindergarten_remove_contactmodel_kindergarten_name_and_more'),
        ('groups', '0002_remove_groups_photo_groups_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.kindergarten'),
        ),
    ]
